# a placeholder pyflakes linter that will be modified soon
name: Pyflakes Linter

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes
  
      - name: Run Pyflakes
        run: pyflakes $(git ls-files '*.py') > pyflakes_report.txt

      - name: Upload Pyflakes Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyflakes-report
          path: post_traces/pyflakes_report.txt
